version: "2.4"

services:
  libraryit-server:
    container_name: libraryit-server
    build: .
    ports:
      - "445:445"
    volumes:
      - ./data/ebooks:/libraryit/ebooks
      - ./data/papers:/libraryit/papers
      - ./data/sourcecode:/libraryit/sourcecode
      - ./data/docs:/libraryit/docs
      - ./logs:/libraryit/logs
    restart: unless-stopped

  libraryit-logger:
    container_name: libraryit-logger
    image: alpine:3.20
    depends_on:
      libraryit-server:
        condition: service_started
    volumes:
      - ./logs:/logs:ro
    command: ["sh", "-c", "tail -F /logs/libraryit.log"]
    restart: unless-stopped
