[global]
   workgroup = WORKGROUP
   server string = LibraryIT
   security = user
   map to guest = never
   guest ok = no
   server role = standalone server
   disable spoolss = yes
   load printers = no
   printing = bsd
   smb ports = 139 445
   log file = /var/log/samba/log.%m
   log level = 1
   max log size = 1000
   hide unreadable = yes
   inherit acls = yes
   map acl inherit = yes

   vfs objects = full_audit
   full_audit:prefix = %u|%S|%a|%p
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[ebooks]
   path = /libraryit/ebooks
   valid users = @staff @readonly
   read only = yes
   write list = @staff
   browseable = yes
   force group = staff
   create mask = 0664
   directory mask = 2775

[papers]
   path = /libraryit/papers
   valid users = @staff @readonly
   read only = yes
   write list = @staff
   browseable = yes
   force group = staff
   create mask = 0664
   directory mask = 2775

[sourcecode]
   path = /libraryit/sourcecode
   valid users = @staff
   read only = no
   browseable = no
   force group = staff
   create mask = 0660
   directory mask = 2770

[docs]
   path = /libraryit/docs
   valid users = @staff @readonly
   read only = yes
   write list = @docswriter
   browseable = yes
   force group = staff
   create mask = 0664
   directory mask = 2775
