[global]
workgroup = WORKGROUP
server string = LibraryIT Server
security = user
map to guest = never
guest ok = no
passdb backend = tdbsam
smb ports = 445
access based share enum = yes
root preexec = /usr/local/bin/libraryit-preexec.sh %u %S

log file = /logs/samba_audit.log
max log size = 0
log level = 1

vfs objects = full_audit
full_audit:prefix = %t|%u|%S
full_audit:success = all
full_audit:failure = all
full_audit:syslog = no

[ebooks]
path = /libraryit/ebooks
valid users = @readonly @staff
read only = no
create mask = 0664
directory mask = 2775

[papers]
path = /libraryit/papers
valid users = @readonly @staff
read only = no
create mask = 0664
directory mask = 2775

[sourcecode]
path = /libraryit/sourcecode
valid users = @staff
read only = no
force user = root
force group = staff
create mask = 0660
directory mask = 2770

[docs]
path = /libraryit/docs
valid users = @readonly @staff
read only = no
create mask = 0644
directory mask = 0755
